apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudmart-config
  namespace: cloudmart
data:
  DATABASE_URL: "postgres://cloudmart:cloudmart@postgres:5432/cloudmart?sslmode=disable"
  REDIS_URL: "redis://redis:6379"
  NATS_URL: "nats://nats:4222"
  JAEGER_ENDPOINT: "http://jaeger:4318"
  JWT_SECRET: "cloudmart-jwt-secret-k8s"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_FROM: "noreply@cloudmart.dev"
  USER_SERVICE_URL: "http://user-service:8081"
  PRODUCT_SERVICE_URL: "http://product-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  INVENTORY_SERVICE_URL: "http://inventory-service:8085"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8086"
